[myservers]
172.16.104.130
172.16.104.131

[myservers:vars]
; ansible_python_interpreter=/usr/bin/python3
ansible_user=ilham
ansible_ssh_private_key_file=~/.ssh/id_rsa

; [all]
; 172.16.104.130 ansible_user=ilham ansible_connection=ssh ansible_python_interpreter=/usr/bin/python3
; 172.16.104.131 ansible_user=ilham ansible_connection=ssh ansible_python_interpreter=/usr/bin/python3